groups:
  - name: infraestructura
    rules:
      - alert: CPUAlta
        expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "CPU alta en {{ $labels.instance }}"
          description: "CPU al {{ $value }}% por más de 2 minutos"

      - alert: RAMAlta
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "RAM alta en {{ $labels.instance }}"
          description: "RAM al {{ $value }}% por más de 2 minutos"

      - alert: DiscoLleno
        expr: (1 - (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"})) * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disco casi lleno en {{ $labels.instance }}"
          description: "Disco al {{ $value }}% de uso"

      - alert: ServicioDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Servicio caído: {{ $labels.job }}"
          description: "El servicio {{ $labels.job }} no responde"