[Infraestructura]
# Definimos los "nombres lógicos"
servidor_dns   ansible_host=192.168.1.2
servidor_dhcp  ansible_host=192.168.1.3
servidor_ldap  ansible_host=192.168.1.4
servidor_sftp  ansible_host=192.168.1.5

[all:vars]
# Variables globales
ansible_user=adminitrador
ansible_ssh_pass=1234
dominio_red=luthor.corp
