---
# PLAY 1: Configurar Servidor DNS
- name: Configurar Servidor DNS
  hosts: dns_server
  become: yes
  roles:
    - role: dns
      tags: ['dns'] 

# PLAY 2: Configurar Servidor DNS
- name: Configurar Servidor DHCP
  hosts: servidor-dhcp
  become: yes
  roles:
    - role: dhcp
      tags: ['dhcp'] 


# PLAY 3: Configurar Servidor LDAP
- name: Configurar Servidor LDAP
  hosts: servidor-ldap
  become: yes
  roles:
    - role: ldap
      tags: ['ldap']  

# PLAY 4: Configurar Servidor SFTP
- name: Configurar Servidor SFTP
  hosts: sftp_server
  become: yes
  roles:
    - role: sftp-ssh
      tags: ['sftp-ssh'] 


