- name: Copiar script Crear.sh al servidor
  copy:
    src: Crear.sh
    dest: /home/administrador-ldap/Crear.sh
    mode: '0755'
    owner: administrador-ldap
    group: administrador-ldap

- name: Crear las OUs iniciales usando el script
  script: Crear.sh 4 "{{ item }}"
  with_items:
    - Users
    - Groups
    - Machines
    - Service

- name: Crear grupos Samba 
  script: Crear.sh 3 

- name: Crear las Grupos iniciales usando el script
  script: Crear.sh 2 "{{ item }}"
  with_items:
    -  soporte
    - desarrollo
    - administracion
    - rr-hh
    - QA

- name: Crear usuarios masivamente por áreas
  script: Crear.sh 1 "{{ item.area }}" "{{ item.cantidad }}"
  register: crear_output
  loop:
    - { area: 'QA', cantidad: 3 }
    - { area: 'administracion', cantidad: 5 }
    - { area: 'rr-hh', cantidad: 3 }
    - { area: 'desarrollo', cantidad: 3 }
    - { area: 'soporte', cantidad: 3 }

- name: Mostrar salida del script
  debug:
    var: crear_output
