# tasks/libpam.yml - Solo seleccionar servicios PAM
- name: Configurar respuestas para libpam-ldapd (seleccionar todos los servicios)
  debconf:
    name: "libpam-ldapd"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    # Seleccionar TODOS: unix, winbind, ldap, systemd, mkhomedir, capability
    - { question: 'libpam-ldapd/profiles', value: 'unix, winbind, ldap, systemd, mkhomedir, capability', vtype: 'multiselect' }