---
# tasks file for Roles/ldap
#1. Actualizar repositorios y reiniciar
- name: Actualizar repositorios y paquetes y Reiniciar
  import_tasks: Actualizar-Reiniciar.yml

# 2. Crear directorio Plantillas
- name: Crear Carpeta de plantillas
  import_tasks: CrearDirectorioPlantillas.yml

# 3. DEBCONF SLAPD
- name: Incluir debconf de slapd
  import_tasks: slapd.yml

# 4. Creacion OU, Grupos y Usuarios
- name: Crear  LDAP
  import_tasks: Crear-Elementos-LDAP.yml




