---
# tasks file for Roles/ldap
- name: Actualizar repositorios y paquetes y Reiniciar
  import_tasks: 01-sistema.yml

- name: Crear Carpeta de plantillas
  import_tasks: 02-CopiarPlantillas.yml

- name: Instalar  slapd
  import_tasks: 03-slapd.yml

- name: Instalar Samba
  import_tasks: 04-samba.yml

- name: Crear  LDAP
  import_tasks: 05-Crear-Elementos-LDAP.yml

- name: Instalar sssd
  import_tasks: 06-sssd.yml

- name: Instalar sssd
  import_tasks: 07-ModoAnonimo-ACL.yml