---
# Task/Samba-Schema.yml

- name: Copiar esquemas de Samba al directorio de LDAP
  copy:
    src: "/usr/share/doc/samba/examples/LDAP/{{ item }}"
    dest: "/etc/ldap/schema/{{ item }}"
    remote_src: yes  
    owner: root
    group: root
    mode: '0644'
  with_items:
    - samba.ldif
    - samba.schema

- name: Agregar el esquema de Samba a la configuración de OpenLDAP
  shell: "ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/samba.ldif"
  register: ldap_schema_result
  # Esto evita que el playbook falle si el esquema ya fue agregado antes
  failed_when: 
    - ldap_schema_result.rc != 0 
    - "'Already exists' not in ldap_schema_result.stderr"
    - "'Other (e.g., implementation specific) error' not in ldap_schema_result.stderr"

