---
# Creás el directorio por las dudas (a veces no existe)
- name: Asegurar que existe el directorio de sssd
  file:
    path: /etc/sssd
    state: directory
    owner: root
    group: root
    mode: '0755'

# Desplegás el template
- name: Configurar sssd.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: '0600'
  notify: Reiniciar SSSD

# Habilitás el servicio
- name: Habilitar SSSD en el arranque
  systemd:
    name: sssd
    enabled: yes
    daemon_reload: yes