---
# 1. Pre-configuración de nslcd (Debconf) para que no pida IP por pantalla
- name: Configurar debconf para nslcd
  debconf:
    name: "nslcd"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: 'nslcd/ldap-uris', value: 'ldap://auth.luthor.corp', vtype: 'string' }
    - { question: 'nslcd/ldap-base', value: "{{ ldap_base_dn }}", vtype: 'string' }
    - { question: 'nslcd/ldap-binddn', value: "cn=servicioUser,ou=Service,{{ ldap_base_dn }}", vtype: 'string' }
    - { question: 'nslcd/ldap-bindpw', value: "service", vtype: 'password' }

- name: Configurar debconf para libnss-ldapd
  debconf:
    name: "libnss-ldapd"
    question: "libnss-ldapd/nsswitch"
    value: "group, passwd, shadow"
    vtype: "multiselect"

# 2. Instalación de paquetes (sin sssd en la lista)
- name: Instalar nslcd y dependencias de red
  apt:
    name:
      - nslcd
      - libnss-ldapd
      - libpam-ldapd
      - ldap-utils 
      - nscd
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive


# 4. Asegurar que nsswitch.conf use ldap
- name: Configurar nsswitch.conf para usar ldap
  replace:
    path: /etc/nsswitch.conf
    regexp: '^(passwd|group|shadow):(\s+)files(.*)$'
    replace: '\1:          files ldap'

# 5. Reiniciar y habilitar servicios
- name: Asegurar que nslcd esté iniciado
  service:
    name: nslcd
    state: restarted
    enabled: yes

- name: Asegurar que nscd esté iniciado
  service:
    name: nscd
    state: restarted
    enabled: yes

- name: Asegurar creación de directorios home al loguearse
  lineinfile:
    path: /etc/pam.d/common-session
    line: "session optional pam_mkhomedir.so skel=/etc/skel umask=077"