---
# tasks file for Roles/ldap
- name: Actualizar repositorios y paquetes y Reiniciar
  import_tasks: ../../TareasComunes/01-sistema.yml

- name: Instalar Dependencias
  import_tasks: ../../TareasComunes/02-nslcd.yml

- name: Instalar Dependencias
  import_tasks: 03-Config-PAM.yml