---
# vars file for Roles/ldap
ldap_domain: "luthor.corp"
ldap_base_dn: "dc=luthor,dc=corp"
ldap_admin_pass: "1234"
ldap_organization: "luthor.corp"
ldap_uri: "ldap://auth.luthor.corp"
ldap_service_user_dn: "cn=servicioUser,ou=Service,dc=luthor,dc=corp"
ldap_admin_dn: "cn=admin,dc=luthor,dc=corp"
ldap_service_user_pass: "service"
