# Instalación de paquete
- name: Instalación de bind9
  apt:
    name:
      - bind9
      - bind9utils
      - dnsutils
    state: present
    update_cache: yes

- name: Asegurar que el directorio de zonas existe
  file:
    path: /etc/bind/zones
    state: directory
    owner: root
    group: bind
    mode: '0755'

- name: Desplegar configuración de opciones (forwarders)
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: '0644'
  notify: Reiniciar BIND9

- name: Desplegar configuración de zonas locales
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: '0644'
  notify: Reiniciar BIND9

- name: Desplegar archivo de Zona Directa
  template:
    src: db.luthor.corp.j2
    dest: "/etc/bind/zones/db.{{ dns_domain }}"
    owner: root
    group: bind
    mode: '0644'
  notify: Reiniciar BIND9

- name: Desplegar archivo de Zona Inversa
  template:
    src: db.58.168.192.j2
    dest: /etc/bind/zones/db.58.168.192
    owner: root
    group: bind
    mode: '0644'
  notify: Reiniciar BIND9

- name: Deshabilitar systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no

# Eliminar el symlink que genera systemd-resolved
- name: Eliminar symlink de resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

# Crear el resolv.conf apuntando a tu DNS
- name: Configurar resolv.conf
  copy:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
    content: |
      nameserver "127.0.0.1"
      search {{ dns_domain }}

# Asegurar que nsswitch use DNS
- name: Configurar nsswitch.conf para usar DNS
  lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts:'
    line: 'hosts: files dns'

- name: Asegurar que BIND9 esté iniciado y habilitado
  service:
    name: named
    state: started
    enabled: yes