---
# tasks file for Roles/dns
- name: Actualizar repositorios y paquetes y Reiniciar
  import_tasks: ../../TareasComunes/01-sistema.yml

- name: Actualizar repositorios y paquetes y Reiniciar
  import_tasks: 02-InstalarDependencias.yml