---
# vars file for Roles/dns
dns_domain: "luthor.corp"
dns_server_ip: "192.168.58.2"
dhcp_tsig_secret: "1234"
dns_forwarders:
  - "8.8.8.8"
  - "8.8.4.4"
  - "1.1.1.1"
  - "9.9.9.9"

# Lista de hosts para generar el archivo de zona
dns_hosts:
  - { name: "ns", ip: "192.168.58.2" }
  - { name: "auth", ip: "192.168.58.4" }
  - { name: "sftp", ip: "192.168.58.5" }
  - { name: "ssh", ip: "192.168.58.5" }