---
# tasks file for Roles/sftp-ssh
- name: Actualizar repositorios y paquetes y Reiniciar
  import_tasks:  ../../TareasComunes/01-sistema.yml

- name: resolv.config
  import_tasks: 02-resolv-config.yml

- name: Instalar NSLCD
  import_tasks: ../../TareasComunes/02-nslcd.yml

- name: ConfigurarPAM
  import_tasks: 03-Pam-config.yml

- name: Crear Grupo de administradores SSH
  import_tasks: 04-Administradores.yml

- name: Crear jaula sftp
  import_tasks: 05-Chroot.yml